# Generated by Django 5.0.2 on 2024-02-14 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0011_auto_20200609_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_state',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
