# Generated by Django 5.0.2 on 2024-02-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gstbillingapp', '0012_customer_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
